// Class: ReadLD
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : LD::LD
TMVA Release   : 4.1.0         [262400]
ROOT Release   : 5.28/00       [334848]
Creator        : mdjordje
Date           : Fri Sep  5 12:33:37 2014
Host           : Linux lxbuild148.cern.ch 2.6.18-194.26.1.el5 #1 SMP Wed Nov 10 09:45:46 CET 2010 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/user/m/mdjordje/CMSSW_7_0_6_patch1/src/CMGTools/TTHAnalysis/macros/leptons
Training events: 16280
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
# Default:
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
relIso03-chargedHadRelIso03   neuRelIso03                   neuRelIso03                   neuRelIso03                                                     'D'    [0,0.399435043335]
chargedHadRelIso03            chRelIso03                    chRelIso03                    chRelIso03                                                      'D'    [0,0.39991736412]
min(jetDR,0.5)                jetDR                         jetDR                         jetDR                                                           'D'    [0,0.389075636864]
min(jetPtRatio,1.5)           jetPtRatio                    jetPtRatio                    jetPtRatio                                                      'D'    [0.0473215691745,1.5]
max(jetBTagCSV,0)             jetBTagCSV                    jetBTagCSV                    jetBTagCSV                                                      'D'    [0,0.999999940395]
sip3d                         sip3d                         sip3d                         sip3d                                                           'D'    [0.00419093947858,587.908691406]
log(abs(dxy))                 dxy                           dxy                           dxy                                                             'D'    [-15.5755329132,-2.99644398689]
log(abs(dz))                  dz                            dz                            dz                                                              'D'    [-14.3435764313,-1.61489140987]
mvaId                         mvaId                         mvaId                         mvaId                                                           'D'    [-0.649863541126,0.999775588512]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadLD : public IClassifierReader {

 public:

   // constructor
   ReadLD( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadLD" ),
        fNvars( 9 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "relIso03-chargedHadRelIso03", "chargedHadRelIso03", "min(jetDR,0.5)", "min(jetPtRatio,1.5)", "max(jetBTagCSV,0)", "sip3d", "log(abs(dxy))", "log(abs(dz))", "mvaId" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0.399435043334961;
      fVmin[1] = 0;
      fVmax[1] = 0.399917364120483;
      fVmin[2] = 0;
      fVmax[2] = 0.389075636863708;
      fVmin[3] = 0.0473215691745281;
      fVmax[3] = 1.5;
      fVmin[4] = 0;
      fVmax[4] = 0.999999940395355;
      fVmin[5] = 0.00419093947857618;
      fVmax[5] = 587.90869140625;
      fVmin[6] = -15.575532913208;
      fVmax[6] = -2.9964439868927;
      fVmin[7] = -14.3435764312744;
      fVmax[7] = -1.61489140987396;
      fVmin[8] = -0.649863541126251;
      fVmax[8] = 0.999775588512421;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadLD() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<double> fLDCoefficients;
};

inline void ReadLD::Initialize() 
{
   fLDCoefficients.push_back( -0.382537042201 );
   fLDCoefficients.push_back( -1.14811082878 );
   fLDCoefficients.push_back( -1.30233409499 );
   fLDCoefficients.push_back( 1.52412225479 );
   fLDCoefficients.push_back( 0.617063856401 );
   fLDCoefficients.push_back( -0.160825487798 );
   fLDCoefficients.push_back( -0.000377963811004 );
   fLDCoefficients.push_back( -0.0415538225043 );
   fLDCoefficients.push_back( -0.0321422613732 );
   fLDCoefficients.push_back( 0.21432708196 );

   // sanity check
   if (fLDCoefficients.size() != fNvars+1) {
      std::cout << "Problem in class \"" << fClassName << "\"::Initialize: mismatch in number of input values"
                << fLDCoefficients.size() << " != " << fNvars+1 << std::endl;
      fStatusIsClean = false;
   }         
}

inline double ReadLD::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double retval = fLDCoefficients[0];
   for (size_t ivar = 1; ivar < fNvars+1; ivar++) {
      retval += fLDCoefficients[ivar]*inputValues[ivar-1];
   }

   return retval;
}

// Clean up
inline void ReadLD::Clear() 
{
   // clear coefficients
   fLDCoefficients.clear(); 
}
   inline double ReadLD::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
