// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/10       [336394]
Creator        : cirkovic
Date           : Wed Aug  6 16:50:33 2014
Host           : Linux cmsdev04.cern.ch 2.6.32-431.11.2.el6.x86_64 #1 SMP Wed Mar 26 09:39:43 CET 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/c/cirkovic/Milos_11-07-2014/CMSSW_7_0_6_patch1/src/CMGTools/TTHAnalysis/macros/finalMVA/2lss
Training events: 8057
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
NTrees: "200" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
nEventsMin: "100" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "200" [Number of steps during node cut optimisation]
NNodesMax: "5" [Max number of nodes in tree]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "2" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "8057" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
min(mhtJet25,300)             mhtJet25                      mhtJet25                      mhtJet25                                                        'F'    [1.52035415173,300]
min(Jet_pt[0],300)            jet1Pt                        jet1Pt                        jet1Pt                                                          'F'    [33.5812759399,300]
min(Jet_pt[1],300)            jet2Pt                        jet2Pt                        jet2Pt                                                          'F'    [26.9142990112,300]
min(htJet25,1000)             htJet25                       htJet25                       htJet25                                                         'F'    [196.166366577,1000]
min(max(bestMTopHadPt,0),400) bestMTopHadPt                 bestMTopHadPt                 bestMTopHadPt                                                   'F'    [0,400]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "min(mhtJet25,300)", "min(Jet_pt[0],300)", "min(Jet_pt[1],300)", "min(htJet25,1000)", "min(max(bestMTopHadPt,0),400)" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 1.52035415172577;
      fVmax[0] = 300;
      fVmin[1] = 33.5812759399414;
      fVmax[1] = 300;
      fVmin[2] = 26.9142990112305;
      fVmax[2] = 300;
      fVmin[3] = 196.166366577148;
      fVmax[3] = 1000;
      fVmin[4] = 0;
      fVmax[4] = 400;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0966324) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.959604,0.0919209) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.909774,0.0819549) , 
3, 283.065, 0, 0, 0.954681,0.454681) , 
3, 388.127, 0, 0, 0.978404,0.478404)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.087814) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.964365,0.0844976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.935268,0.0786376) , 
0, 56.1653, 0, 0, 0.954681,0.409338) , 
3, 388.127, 0, 0, 0.978404,0.430709)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0810915) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.959604,0.076944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.909774,0.0674542) , 
3, 283.065, 0, 0, 0.954681,0.3688) , 
3, 388.127, 0, 0, 0.978404,0.3881)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0757879) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.988764,0.0777977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.949486,0.0696443) , 
0, 129.46, 0, 0, 0.954681,0.332466) , 
3, 388.127, 0, 0, 0.978404,0.349926)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0714884) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.959604,0.0673032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.909774,0.0575844) , 
3, 283.065, 0, 0, 0.954681,0.299839) , 
3, 388.127, 0, 0, 0.978404,0.315659)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0679231) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.964365,0.0647051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.935268,0.0584015) , 
0, 56.1653, 0, 0, 0.954681,0.270503) , 
3, 388.127, 0, 0, 0.978404,0.284854)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.992104,0.0671471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975923,0.063355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,0.0506119) , 
3, 284.148, 0, 0, 0.974539,0.25386) , 
4, 197.015, 0, 0, 0.978404,0.257131)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0623367) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957997,0.057236) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.916667,0.0461456) , 
1, 124.41, 1, 0, 0.954681,0.219262) , 
3, 388.127, 0, 0, 0.978404,0.23216)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985693,0.0608471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.972532,0.0575284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930556,0.0457518) , 
4, 113.507, 1, 0, 0.971022,0.204093) , 
4, 117.413, 0, 0, 0.978404,0.209654)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.992104,0.0606654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.975923,0.0561993) , 
4, 197.015, 0, 0, 0.979545,0.190072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,0.0410966) , 
3, 284.148, 0, 0, 0.978404,0.189357)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0562893) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.959714,0.0505118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930131,0.0409974) , 
2, 73.3729, 1, 0, 0.954681,0.158945) , 
3, 388.127, 0, 0, 0.978404,0.171045)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.993553,0.0580722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.976548,0.0526628) , 
4, 218.905, 0, 0, 0.979545,0.155174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,0.0358853) , 
3, 284.148, 0, 0, 0.978404,0.154519)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.053125) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.964365,0.047942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.935268,0.0384527) , 
0, 56.1653, 0, 0, 0.954681,0.128429) , 
3, 388.127, 0, 0, 0.978404,0.139598)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.05169) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.988764,0.0550514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.949486,0.041072) , 
0, 129.46, 0, 0, 0.954681,0.115963) , 
3, 388.127, 0, 0, 0.978404,0.126125)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.992104,0.054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.975923,0.0476901) , 
4, 197.015, 0, 0, 0.979545,0.114549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,0.0285987) , 
3, 284.148, 0, 0, 0.978404,0.113955)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985693,0.0502291) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.972532,0.0449914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930556,0.0267287) , 
4, 113.507, 1, 0, 0.971022,0.0986185) , 
4, 117.413, 0, 0, 0.978404,0.102961)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0478296) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957997,0.0386302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.916667,0.0193946) , 
1, 124.41, 1, 0, 0.954681,0.0829408) , 
3, 388.127, 0, 0, 0.978404,0.0930274)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.998459,0.0546453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.977857,0.0441998) , 
4, 280.597, 0, 0, 0.979545,0.0846295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,0.0212677) , 
3, 284.148, 0, 0, 0.978404,0.0840521)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0454127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.959714,0.0360713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930131,0.0206301) , 
2, 73.3729, 1, 0, 0.954681,0.0663724) , 
3, 388.127, 0, 0, 0.978404,0.0759401)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.992908,0.0499534) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.976291,0.0406967) , 
4, 208.955, 0, 0, 0.979545,0.0691466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,0.0171578) , 
3, 284.148, 0, 0, 0.978404,0.0686097)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984737,0.0440335) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.973399,0.0383637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.955727,0.0284877) , 
0, 61.1924, 0, 0, 0.967025,0.0565283) , 
3, 472.109, 0, 0, 0.978404,0.0619836)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0418442) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957997,0.030065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.916667,0.00550092) , 
1, 124.41, 1, 0, 0.954681,0.0470689) , 
3, 388.127, 0, 0, 0.978404,0.0559944)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985693,0.0425475) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.972286,0.034269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.924528,0.00248886) , 
4, 114.09, 1, 0, 0.971022,0.0466127) , 
4, 117.413, 0, 0, 0.978404,0.0505818)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.998459,0.0517762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.977857,0.0360044) , 
4, 280.597, 0, 0, 0.979545,0.0462309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,0.0078199) , 
3, 284.148, 0, 0, 0.978404,0.0456882)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0382451) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.988764,0.0456088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.949486,0.0192691) , 
0, 129.46, 0, 0, 0.954681,0.0322319) , 
3, 388.127, 0, 0, 0.978404,0.041265)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.992104,0.0447423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.975923,0.0318666) , 
4, 197.015, 0, 0, 0.979545,0.0377555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,0.0052193) , 
3, 284.148, 0, 0, 0.978404,0.0372686)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0357352) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97561,0.0370879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.95092,0.0157728) , 
1, 62.6817, 1, 0, 0.954681,0.0252612) , 
3, 388.127, 0, 0, 0.978404,0.0336553)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981616,0.0337647) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975435,0.0281179) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.906832,-0.0117017) , 
3, 320.141, 0, 0, 0.970833,0.0249642) , 
0, 60.9193, 0, 0, 0.978404,0.0303902)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985693,0.035867) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.972532,0.0252598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930556,-0.0107885) , 
4, 113.507, 1, 0, 0.971022,0.023804) , 
4, 117.413, 0, 0, 0.978404,0.0274389)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0319335) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.959714,0.0187116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930131,-0.00804475) , 
2, 73.3729, 1, 0, 0.954681,0.0164756) , 
3, 388.127, 0, 0, 0.978404,0.0247719)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.995238,0.0450341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.977147,0.0254175) , 
4, 244.776, 0, 0, 0.979545,0.0228439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,-0.00361478) , 
3, 284.148, 0, 0, 0.978404,0.0223628)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984737,0.0311189) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.968266,0.0185954) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.947368,-0.0151475) , 
2, 102.018, 1, 0, 0.967025,0.0155641) , 
3, 472.109, 0, 0, 0.978404,0.0201851)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0280315) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957997,0.0131376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.916667,-0.0260431) , 
1, 124.41, 1, 0, 0.954681,0.0105128) , 
3, 388.127, 0, 0, 0.978404,0.0182178)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.992104,0.0383202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.975923,0.0201554) , 
4, 197.015, 0, 0, 0.979545,0.0168917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,-0.0066687) , 
3, 284.148, 0, 0, 0.978404,0.0164414)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981616,0.0249348) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975435,0.0175074) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.906832,-0.0226649) , 
3, 320.141, 0, 0, 0.970833,0.00977447) , 
0, 60.9193, 0, 0, 0.978404,0.0148363)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985693,0.0277689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.972532,0.0152619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930556,-0.0275166) , 
4, 113.507, 1, 0, 0.971022,0.0100928) , 
4, 117.413, 0, 0, 0.978404,0.0133864)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0230094) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97561,0.0299138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.95092,-8.56274e-05) , 
1, 62.6817, 1, 0, 0.954681,0.00470408) , 
3, 388.127, 0, 0, 0.978404,0.0120778)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.998459,0.0477922) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.977479,0.0170848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.964657,-0.010505) , 
1, 298.675, 1, 0, 0.976647,0.00995138) , 
4, 280.597, 0, 0, 0.978404,0.0108962)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.989835,0.0317014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.976993,0.0142645) , 
3, 754.308, 0, 0, 0.979545,0.0102698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,-0.0117116) , 
3, 284.148, 0, 0, 0.978404,0.00982957)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0195105) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.959714,0.00757951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930131,-0.0255618) , 
2, 73.3729, 1, 0, 0.954681,0.00173251) , 
3, 388.127, 0, 0, 0.978404,0.00886539)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981616,0.0181761) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975024,0.0117963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.946927,-0.0314421) , 
0, 55.0089, 1, 0, 0.970833,0.00326444) , 
0, 60.9193, 0, 0, 0.978404,0.00799665)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.992104,0.031904) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975365,0.0109795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.962312,-0.0199535) , 
1, 298.675, 1, 0, 0.974539,0.00554328) , 
4, 197.015, 0, 0, 0.978404,0.00721351)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.986842,0.0335081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.979329,0.0122188) , 
1, 65.4273, 1, 0, 0.979545,0.00693234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,-0.0140153) , 
3, 284.148, 0, 0, 0.978404,0.00650673)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0155218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957997,0.00218835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.916667,-0.0434269) , 
1, 124.41, 1, 0, 0.954681,-0.0013474) , 
3, 388.127, 0, 0, 0.978404,0.0058655)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985693,0.0188457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.972286,0.00544125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.924528,-0.0474126) , 
4, 114.09, 1, 0, 0.971022,0.00221681) , 
4, 117.413, 0, 0, 0.978404,0.00528995)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98973,0.0261905) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976246,0.00740983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.94,-0.0910647) , 
2, 175.814, 1, 0, 0.975689,0.00332845) , 
3, 756.05, 0, 0, 0.978404,0.00477128)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.0128459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.988764,0.0360723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.949486,-0.0078774) , 
0, 129.46, 0, 0, 0.954681,-0.00235633) , 
3, 388.127, 0, 0, 0.978404,0.00430588)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.993553,0.0312232) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975965,0.00655247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.964286,-0.0243671) , 
1, 298.675, 1, 0, 0.975229,0.00254902) , 
4, 218.905, 0, 0, 0.978404,0.00388352)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.986842,0.0313319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.979329,0.00725749) , 
1, 65.4273, 1, 0, 0.979545,0.00388315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,-0.0143541) , 
3, 284.148, 0, 0, 0.978404,0.0035035)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984737,0.0131937) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.968266,0.0015077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.947368,-0.0545774) , 
2, 102.018, 1, 0, 0.967025,-0.000717142) , 
3, 472.109, 0, 0, 0.978404,0.00315739)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981427,0.0102841) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975597,0.00531992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.945946,-0.0444119) , 
0, 53.3579, 1, 0, 0.970819,-0.00167267) , 
0, 59.4343, 0, 0, 0.978404,0.00284904)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980645,0.0285618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979713,0.00629408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.91411,-0.0276142) , 
3, 300.145, 0, 0, 0.97836,0.00217339) , 
1, 58.7651, 1, 0, 0.978404,0.00257255)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.998459,0.0448073) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.977479,0.00510295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.964657,-0.028653) , 
1, 298.675, 1, 0, 0.976647,0.00149216) , 
4, 280.597, 0, 0, 0.978404,0.00231948)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.00851778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.959714,0.000668549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930131,-0.0341263) , 
2, 73.3729, 1, 0, 0.954681,-0.00426376) , 
3, 388.127, 0, 0, 0.978404,0.00209468)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98973,0.0214313) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976246,0.00239266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.94,-0.0872254) , 
2, 175.814, 1, 0, 0.975689,0.000557079) , 
3, 756.05, 0, 0, 0.978404,0.00188999)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985693,0.0119028) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.972532,0.000318929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930556,-0.0431725) , 
4, 113.507, 1, 0, 0.971022,-0.000965967) , 
4, 117.413, 0, 0, 0.978404,0.00170824)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981616,0.0076713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975435,-0.000205636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.906832,-0.0322774) , 
3, 320.141, 0, 0, 0.970833,-0.00244408) , 
0, 60.9193, 0, 0, 0.978404,0.00154217)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980645,0.0271793) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979713,0.00370674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.91411,-0.0232294) , 
3, 300.145, 0, 0, 0.97836,0.00101272) , 
1, 58.7651, 1, 0, 0.978404,0.0013916)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.994144,0.0286285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.975031,0.000225268) , 
4, 208.955, 0, 0, 0.978729,0.00155732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.955357,-0.0424714) , 
0, 11.9152, 0, 0, 0.978404,0.00125501)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980645,0.0257809) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979713,0.00308171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.91411,-0.0200383) , 
3, 300.145, 0, 0, 0.97836,0.000789873) , 
1, 58.7651, 1, 0, 0.978404,0.00113462)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00393395) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.0505444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.962472,-0.0347959) , 
4, 244.776, 0, 0, 0.974046,-0.00724889) , 
1, 298.675, 1, 0, 0.978404,0.00102318)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98973,0.0188309) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976564,0.00423945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.972678,-0.0231501) , 
1, 170.104, 1, 0, 0.975689,-0.000296772) , 
3, 756.05, 0, 0, 0.978404,0.00092562)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984737,0.00770533) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.968266,-0.00169987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.947368,-0.0532656) , 
2, 102.018, 1, 0, 0.967025,-0.00253541) , 
3, 472.109, 0, 0, 0.978404,0.000839159)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.00501802) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957997,-0.00197915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.916667,-0.0482398) , 
1, 124.41, 1, 0, 0.954681,-0.00461147) , 
3, 388.127, 0, 0, 0.978404,0.000759536)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00319986) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981859,0.000943332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.957944,-0.0645631) , 
0, 210.731, 1, 0, 0.974046,-0.00744166) , 
1, 298.675, 1, 0, 0.978404,0.000686773)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981616,0.00543152) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975024,0.000922778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.946927,-0.0397755) , 
0, 55.0089, 1, 0, 0.970833,-0.00304571) , 
0, 60.9193, 0, 0, 0.978404,0.000622499)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.0505065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.976849,9.95246e-05) , 
4, 280.597, 0, 0, 0.978729,0.000838899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.955357,-0.037741) , 
0, 11.9152, 0, 0, 0.978404,0.000564893)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980645,0.0241081) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979713,0.00161868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.91411,-0.0183118) , 
3, 300.145, 0, 0, 0.97836,0.000198785) , 
1, 58.7651, 1, 0, 0.978404,0.000513126)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00260506) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991304,0.0239687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.964706,-0.0381767) , 
2, 227.827, 0, 0, 0.974046,-0.00707823) , 
1, 298.675, 1, 0, 0.978404,0.000463297)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98973,0.0169041) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976246,-0.000354106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.94,-0.0732113) , 
2, 175.814, 1, 0, 0.975689,-0.000702184) , 
3, 756.05, 0, 0, 0.978404,0.000420687)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.00382217) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.959714,3.21378e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930131,-0.0321839) , 
2, 73.3729, 1, 0, 0.954681,-0.00450528) , 
3, 388.127, 0, 0, 0.978404,0.000383385)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00231285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.0504479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.962472,-0.030047) , 
4, 244.776, 0, 0, 0.974046,-0.00699769) , 
1, 298.675, 1, 0, 0.978404,0.000347717)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981427,0.00431087) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975597,0.00135413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.945946,-0.0387889) , 
0, 53.3579, 1, 0, 0.970819,-0.0031667) , 
0, 59.4343, 0, 0, 0.978404,0.000316425)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978854,0.00150471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980952,0.0194124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.941176,-0.0929182) , 
1, 126.168, 1, 0, 0.961353,-0.0129) , 
0, 16.3701, 0, 0, 0.978404,0.000289164)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984737,0.00556329) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.969214,0.00283098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.963277,-0.0196729) , 
2, 73.3526, 1, 0, 0.967025,-0.00261845) , 
3, 472.109, 0, 0, 0.978404,0.000265098)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985693,0.007123) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.972286,-0.00188485) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.924528,-0.0443927) , 
4, 114.09, 1, 0, 0.971022,-0.00186424) , 
4, 117.413, 0, 0, 0.978404,0.000241823)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000347809) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.990741,0.0405171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.962121,-0.00465858) , 
2, 46.6673, 1, 0, 0.975,0.0121021) , 
1, 62.7415, 0, 0, 0.978404,0.000220391)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980707,0.00285043) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.960526,-0.0182577) , 
2, 50.3787, 0, 0, 0.979545,0.000477379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,-0.011992) , 
3, 284.148, 0, 0, 0.978404,0.000199841)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00186112) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981859,0.000383303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.957944,-0.0509576) , 
0, 210.731, 1, 0, 0.974046,-0.00675536) , 
1, 298.675, 1, 0, 0.978404,0.000181419)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98973,0.0156767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976564,0.0028556) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.972678,-0.0236998) , 
1, 170.104, 1, 0, 0.975689,-0.000888938) , 
3, 756.05, 0, 0, 0.978404,0.000166183)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98576,0.0105411) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976565,0.000132665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.967033,-0.0336273) , 
0, 115.87, 1, 0, 0.97568,-0.00115819) , 
0, 130.713, 0, 0, 0.978404,0.000154742)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.988221,0.0130115) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976256,-0.000493403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958333,-0.0815202) , 
2, 132.48, 1, 0, 0.975782,-0.000896538) , 
2, 136.964, 0, 0, 0.978404,0.000143163)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00175417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.0503909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.962472,-0.0273532) , 
4, 244.776, 0, 0, 0.974046,-0.00680075) , 
1, 298.675, 1, 0, 0.978404,0.000134329)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984064,0.00411891) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.967722,0.00248052) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.955423,-0.0247169) , 
2, 73.3526, 1, 0, 0.964098,-0.00310234) , 
3, 440.116, 0, 0, 0.978404,0.00012381)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980707,0.00250666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.960526,-0.0166142) , 
2, 50.3787, 0, 0, 0.979545,0.000382247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,-0.011547) , 
3, 284.148, 0, 0, 0.978404,0.000114692)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000616337) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.990741,0.0399523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.962121,-0.00360693) , 
2, 46.6673, 1, 0, 0.975,0.0117982) , 
1, 62.7415, 0, 0, 0.978404,0.000104544)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.986842,0.0266056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.979329,-0.000121149) , 
1, 65.4273, 1, 0, 0.979545,0.000356191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,-0.0112179) , 
3, 284.148, 0, 0, 0.978404,9.54973e-05)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981427,0.00343456) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975735,-0.0017361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.901961,-0.0293525) , 
3, 320.141, 0, 0, 0.970819,-0.00303809) , 
0, 59.4343, 0, 0, 0.978404,8.71648e-05)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00154444) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.993976,0.0308036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.96728,-0.0286283) , 
2, 263.913, 0, 0, 0.974046,-0.00641651) , 
1, 298.675, 1, 0, 0.978404,8.04539e-05)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985533,0.00924613) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97662,1.78253e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.959302,-0.0469293) , 
0, 118.323, 1, 0, 0.975589,-0.00115708) , 
0, 127.743, 0, 0, 0.978404,7.50071e-05)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.988142,0.0113452) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976135,0.00154344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.968937,-0.0324768) , 
1, 182.033, 1, 0, 0.975137,-0.00104242) , 
3, 696.063, 0, 0, 0.978404,7.21049e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.994144,0.0228195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.975031,-0.00167468) , 
4, 208.955, 0, 0, 0.978729,0.000297275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.955357,-0.0290707) , 
0, 11.9152, 0, 0, 0.978404,6.98654e-05)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000642805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991667,0.0396323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958333,-0.00599919) , 
4, 49.1393, 1, 0, 0.975,0.0108381) , 
1, 62.7415, 0, 0, 0.978404,6.56073e-05)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00145761) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984615,0.0228473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971429,-0.0311) , 
2, 120.856, 1, 0, 0.974046,-0.00623345) , 
1, 298.675, 1, 0, 0.978404,6.04598e-05)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.989796,0.0143281) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976374,-0.000786667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.945946,-0.0555625) , 
2, 176.933, 1, 0, 0.975862,-0.000821292) , 
3, 768.048, 0, 0, 0.978404,5.70322e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.00250014) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.969112,0.0175682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.951242,-0.0112243) , 
2, 45.9201, 1, 0, 0.954681,-0.00399902) , 
3, 388.127, 0, 0, 0.978404,5.443e-05)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.0014095) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981859,0.000771204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.957944,-0.043554) , 
0, 210.731, 1, 0, 0.974046,-0.0061105) , 
1, 298.675, 1, 0, 0.978404,5.11056e-05)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980492,0.00166371) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.969957,0.00759377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.942308,-0.0313934) , 
4, 64.9851, 0, 0, 0.958869,-0.00561219) , 
2, 54.087, 0, 0, 0.978404,4.82253e-05)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000664985) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991667,0.0391314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958333,-0.00533997) , 
4, 49.1393, 1, 0, 0.975,0.0104753) , 
1, 62.7415, 0, 0, 0.978404,4.61156e-05)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985401,0.00849658) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976607,-0.000121281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.956522,-0.045932) , 
0, 118.182, 1, 0, 0.975559,-0.00112257) , 
0, 126.258, 0, 0, 0.978404,4.28384e-05)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979829,0.00193626) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976371,-0.0025637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.907407,-0.0343649) , 
3, 341.486, 0, 0, 0.969983,-0.00436573) , 
0, 40.1297, 0, 0, 0.978404,4.26281e-05)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.988221,0.0116402) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976256,-0.000600418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958333,-0.0643789) , 
2, 132.48, 1, 0, 0.975782,-0.000879127) , 
2, 136.964, 0, 0, 0.978404,3.99879e-05)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980823,-0.00708761) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.992689,0.026309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.972208,-0.00126028) , 
4, 160.791, 0, 0, 0.977067,0.00135351) , 
1, 170.104, 0, 0, 0.978404,3.99137e-05)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000652206) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.990741,0.038531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.962121,-0.00379423) , 
2, 46.6673, 1, 0, 0.975,0.0100812) , 
1, 62.7415, 0, 0, 0.978404,3.95141e-05)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98973,0.0130566) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976246,-0.000785374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.94,-0.0497756) , 
2, 175.814, 1, 0, 0.975689,-0.000802989) , 
3, 756.05, 0, 0, 0.978404,3.67616e-05)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00134368) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984615,0.0219387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971429,-0.0287526) , 
2, 120.856, 1, 0, 0.974046,-0.00597348) , 
1, 298.675, 1, 0, 0.978404,3.57032e-05)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.988221,0.0117726) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976055,0.00173892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.974684,-0.023076) , 
2, 109.507, 1, 0, 0.975782,-0.000899021) , 
2, 136.964, 0, 0, 0.978404,3.44308e-05)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980492,0.00154727) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.969957,0.00707823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.942308,-0.028455) , 
4, 64.9851, 0, 0, 0.958869,-0.00530997) , 
2, 54.087, 0, 0, 0.978404,3.46797e-05)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000644411) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991667,0.0384528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958333,-0.00519491) , 
4, 49.1393, 1, 0, 0.975,0.00977489) , 
1, 62.7415, 0, 0, 0.978404,3.35043e-05)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981427,0.00290166) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.974212,-0.000192139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.935644,-0.0444331) , 
0, 55.6618, 1, 0, 0.970819,-0.00268222) , 
0, 59.4343, 0, 0, 0.978404,3.13905e-05)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978854,0.000740194) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980952,0.0196865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.941176,-0.06677) , 
1, 126.168, 1, 0, 0.961353,-0.0104542) , 
0, 16.3701, 0, 0, 0.978404,3.15242e-05)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984737,0.00395115) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.968266,-0.00150224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.947368,-0.0408329) , 
2, 102.018, 1, 0, 0.967025,-0.00221444) , 
3, 472.109, 0, 0, 0.978404,3.14044e-05)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00128652) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981859,0.000202779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.957944,-0.0377426) , 
0, 210.731, 1, 0, 0.974046,-0.00575512) , 
1, 298.675, 1, 0, 0.978404,3.05422e-05)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.988142,0.010138) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976122,0.00194941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.970874,-0.0231938) , 
1, 170.104, 1, 0, 0.975137,-0.000947029) , 
3, 696.063, 0, 0, 0.978404,2.92552e-05)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980707,0.00206889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.960526,-0.0152156) , 
2, 50.3787, 0, 0, 0.979545,0.000248197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,-0.00919367) , 
3, 284.148, 0, 0, 0.978404,3.00129e-05)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97868,-0.000667338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991935,0.0426015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.94,-0.0222104) , 
4, 67.5224, 0, 0, 0.96875,0.0105461) , 
2, 41.8593, 0, 0, 0.978404,2.80434e-05)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000641254) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.990741,0.0379082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.962121,-0.00364317) , 
2, 46.6673, 1, 0, 0.975,0.00953143) , 
1, 62.7415, 0, 0, 0.978404,2.75953e-05)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979987,-0.000756445) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971765,0.0133385) , 
3, 337.7, 0, 0, 0.979545,0.000243978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,-0.00919827) , 
3, 284.148, 0, 0, 0.978404,2.59573e-05)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.00225298) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957997,-0.00127364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.916667,-0.0384814) , 
1, 124.41, 1, 0, 0.954681,-0.00373027) , 
3, 388.127, 0, 0, 0.978404,2.4162e-05)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00122438) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984615,0.0215436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971429,-0.0261096) , 
2, 120.856, 1, 0, 0.974046,-0.00553601) , 
1, 298.675, 1, 0, 0.978404,2.35551e-05)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.988221,0.0110356) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976359,0.00164678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.9735,-0.0191908) , 
1, 174.081, 1, 0, 0.975782,-0.000837846) , 
2, 136.964, 0, 0, 0.978404,2.31852e-05)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980433,0.00149951) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.965368,0.0015289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.925234,-0.077527) , 
2, 68.8687, 1, 0, 0.96,-0.00509501) , 
1, 79.9726, 0, 0, 0.978404,2.37911e-05)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985401,0.00780621) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976607,-0.000137867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.956522,-0.0387327) , 
0, 118.182, 1, 0, 0.975559,-0.00103224) , 
0, 126.258, 0, 0, 0.978404,2.59749e-05)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.998459,0.0395247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.977055,0.000424423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971264,-0.0236116) , 
2, 176.364, 1, 0, 0.976647,-0.000461389) , 
4, 280.597, 0, 0, 0.978404,2.65163e-05)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980101,-0.00308972) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979965,0.0110989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.949309,-0.0214525) , 
1, 75.9962, 0, 0, 0.975092,0.00228156) , 
4, 83.5821, 0, 0, 0.978404,2.69136e-05)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000652811) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991667,0.0379029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958333,-0.00374301) , 
4, 49.1393, 1, 0, 0.975,0.00968074) , 
1, 62.7415, 0, 0, 0.978404,2.7595e-05)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979829,0.00167094) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976371,-0.00183138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.907407,-0.0302816) , 
3, 341.486, 0, 0, 0.969983,-0.00381677) , 
0, 40.1297, 0, 0, 0.978404,2.59859e-05)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97868,-0.000611676) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991935,0.0418379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.94,-0.0204489) , 
4, 67.5224, 0, 0, 0.96875,0.00963303) , 
2, 41.8593, 0, 0, 0.978404,2.46652e-05)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000620984) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.990741,0.0370585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.962121,-0.00254871) , 
2, 46.6673, 1, 0, 0.975,0.00914781) , 
1, 62.7415, 0, 0, 0.978404,2.43235e-05)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980492,0.00142073) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.96,0.0108069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958159,-0.0271162) , 
3, 331.579, 1, 0, 0.958869,-0.00495083) , 
2, 54.087, 0, 0, 0.978404,2.29085e-05)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980707,0.00194105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.960526,-0.0137576) , 
2, 50.3787, 0, 0, 0.979545,0.000238407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,-0.00908575) , 
3, 284.148, 0, 0, 0.978404,2.32364e-05)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978853,-0.000787632) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985577,0.0319427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943262,-0.017934) , 
4, 63.2836, 0, 0, 0.968481,0.00753757) , 
2, 45.9352, 0, 0, 0.978404,2.18001e-05)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980101,-0.00295359) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979965,0.0104688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.949309,-0.0187605) , 
1, 75.9962, 0, 0, 0.975092,0.00217431) , 
4, 83.5821, 0, 0, 0.978404,2.16776e-05)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000669035) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991667,0.0376108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958333,-0.00284081) , 
4, 49.1393, 1, 0, 0.975,0.0097162) , 
1, 62.7415, 0, 0, 0.978404,2.23354e-05)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981106,-0.00347582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.997175,0.0445923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.970841,-0.000229709) , 
1, 116.143, 0, 0, 0.973919,0.00205045) , 
1, 122.388, 0, 0, 0.978404,2.12121e-05)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.989796,0.0124917) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976374,-0.00070897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.945946,-0.0401153) , 
2, 176.933, 1, 0, 0.975862,-0.000711338) , 
3, 768.048, 0, 0, 0.978404,2.26829e-05)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00121127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.993976,0.0298197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.96728,-0.0234187) , 
2, 263.913, 0, 0, 0.974046,-0.00548246) , 
1, 298.675, 1, 0, 0.978404,2.23872e-05)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985693,0.00499413) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975092,0.00376241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.962294,-0.0162319) , 
4, 83.2388, 1, 0, 0.971022,-0.00152593) , 
4, 117.413, 0, 0, 0.978404,2.20782e-05)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979466,0.00158803) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984645,0.0162057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.95979,-0.0278206) , 
1, 178.675, 0, 0, 0.971638,-0.00398471) , 
4, 21.8905, 0, 0, 0.978404,2.26194e-05)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00116553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984615,0.0215875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971429,-0.0247021) , 
2, 120.856, 1, 0, 0.974046,-0.00524205) , 
1, 298.675, 1, 0, 0.978404,2.37675e-05)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000600727) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.992806,0.0375595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.950495,-0.00628399) , 
0, 57.6497, 0, 0, 0.975,0.00883861) , 
1, 62.7415, 0, 0, 0.978404,2.32263e-05)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.988221,0.0102751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976055,0.00165709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.974684,-0.0196792) , 
2, 109.507, 1, 0, 0.975782,-0.000763844) , 
2, 136.964, 0, 0, 0.978404,2.20795e-05)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.998459,0.0386702) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.977055,0.000445158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971264,-0.0219601) , 
2, 176.364, 1, 0, 0.976647,-0.000420927) , 
4, 280.597, 0, 0, 0.978404,2.26558e-05)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.987397,0.00824141) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975967,0.00182287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.969104,-0.0240487) , 
1, 170.104, 1, 0, 0.974809,-0.000936233) , 
3, 668.069, 0, 0, 0.978404,2.30928e-05)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984737,0.00368583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.969214,0.00310281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.963277,-0.0166378) , 
2, 73.3526, 1, 0, 0.967025,-0.00206578) , 
3, 472.109, 0, 0, 0.978404,2.41729e-05)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980707,0.00193284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.960526,-0.0138144) , 
2, 50.3787, 0, 0, 0.979545,0.000233462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,-0.0088265) , 
3, 284.148, 0, 0, 0.978404,2.39865e-05)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978853,-0.000758857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985577,0.0311139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943262,-0.0157602) , 
4, 63.2836, 0, 0, 0.968481,0.0072955) , 
2, 45.9352, 0, 0, 0.978404,2.24683e-05)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00111436) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991304,0.0192091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.964706,-0.0220957) , 
2, 227.827, 0, 0, 0.974046,-0.00501363) , 
1, 298.675, 1, 0, 0.978404,2.20608e-05)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.986378,0.00940275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976815,-0.000325379) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.962766,-0.0632831) , 
0, 143.361, 1, 0, 0.976405,-0.000741712) , 
0, 150.018, 0, 0, 0.978404,2.134e-05)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983218,0.00310425) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97115,0.00113029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.952522,-0.0415734) , 
2, 73.423, 1, 0, 0.96882,-0.00208612) , 
2, 77.1838, 0, 0, 0.978404,2.27807e-05)    );
  // itree = 150
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979987,-0.000696233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971765,0.0125171) , 
3, 337.7, 0, 0, 0.979545,0.000223544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,-0.00834261) , 
3, 284.148, 0, 0, 0.978404,2.42436e-05)    );
  // itree = 151
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978854,0.00064285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980952,0.0184934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.941176,-0.0525235) , 
1, 126.168, 1, 0, 0.961353,-0.00923229) , 
0, 16.3701, 0, 0, 0.978404,2.25012e-05)    );
  // itree = 152
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.983162,0.00199003) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.957997,-0.0010372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.916667,-0.0322039) , 
1, 124.41, 1, 0, 0.954681,-0.00326737) , 
3, 388.127, 0, 0, 0.978404,2.238e-05)    );
  // itree = 153
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985401,0.00694387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976607,-3.87195e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.956522,-0.033046) , 
0, 118.182, 1, 0, 0.975559,-0.000901158) , 
0, 126.258, 0, 0, 0.978404,2.14793e-05)    );
  // itree = 154
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00109227) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981859,0.00126631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.957944,-0.0317304) , 
0, 210.731, 1, 0, 0.974046,-0.00490811) , 
1, 298.675, 1, 0, 0.978404,2.17454e-05)    );
  // itree = 155
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981427,0.00247043) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975597,0.00252796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.945946,-0.0323973) , 
0, 53.3579, 1, 0, 0.970819,-0.00227911) , 
0, 59.4343, 0, 0, 0.978404,2.08906e-05)    );
  // itree = 156
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000560567) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.990741,0.036133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.962121,-0.00286208) , 
2, 46.6673, 1, 0, 0.975,0.00825323) , 
1, 62.7415, 0, 0, 0.978404,2.18604e-05)    );
  // itree = 157
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980707,0.00185679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.960526,-0.0134753) , 
2, 50.3787, 0, 0, 0.979545,0.000213801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,-0.00807001) , 
3, 284.148, 0, 0, 0.978404,2.05924e-05)    );
  // itree = 158
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978853,-0.000727633) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985577,0.0301809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943262,-0.013924) , 
4, 63.2836, 0, 0, 0.968481,0.00694366) , 
2, 45.9352, 0, 0, 0.978404,1.9351e-05)    );
  // itree = 159
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979829,0.0015176) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976371,-0.00136141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.907407,-0.0281981) , 
3, 341.486, 0, 0, 0.969983,-0.00348143) , 
0, 40.1297, 0, 0, 0.978404,1.90491e-05)    );
  // itree = 160
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980101,-0.00277336) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979965,0.0100296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.949309,-0.0177384) , 
1, 75.9962, 0, 0, 0.975092,0.00203924) , 
4, 83.5821, 0, 0, 0.978404,1.82509e-05)    );
  // itree = 161
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000639259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991667,0.0370524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958333,-0.00269519) , 
4, 49.1393, 1, 0, 0.975,0.00919559) , 
1, 62.7415, 0, 0, 0.978404,1.89671e-05)    );
  // itree = 162
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981125,-0.00322051) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.0513818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971004,0.000121908) , 
1, 116.272, 0, 0, 0.973746,0.00195869) , 
1, 121.062, 0, 0, 0.978404,1.81037e-05)    );
  // itree = 163
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.0005697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.992806,0.036346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.950495,-0.00442151) , 
0, 57.6497, 0, 0, 0.975,0.00830253) , 
1, 62.7415, 0, 0, 0.978404,1.98112e-05)    );
  // itree = 164
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979466,0.0014335) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984645,0.0153177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.95979,-0.0242518) , 
1, 178.675, 0, 0, 0.971638,-0.00359191) , 
4, 21.8905, 0, 0, 0.978404,1.88408e-05)    );
  // itree = 165
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980823,-0.00568587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.997294,0.0387527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.973708,-0.000380183) , 
4, 190.567, 0, 0, 0.977067,0.0010893) , 
1, 170.104, 0, 0, 0.978404,1.97016e-05)    );
  // itree = 166
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97868,-0.00053071) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991935,0.0394746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.94,-0.0134721) , 
4, 67.5224, 0, 0, 0.96875,0.00834377) , 
2, 41.8593, 0, 0, 0.978404,2.10766e-05)    );
  // itree = 167
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980101,-0.00274998) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979965,0.00973344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.949309,-0.0162047) , 
1, 75.9962, 0, 0, 0.975092,0.00202975) , 
4, 83.5821, 0, 0, 0.978404,2.04894e-05)    );
  // itree = 168
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000580782) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991667,0.036307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958333,-0.00291801) , 
4, 49.1393, 1, 0, 0.975,0.00847802) , 
1, 62.7415, 0, 0, 0.978404,2.07297e-05)    );
  // itree = 169
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979893,-0.0140791) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.996164,0.0359226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.976107,-0.00129725) , 
2, 142.087, 0, 0, 0.978252,0.000463223) , 
2, 176.364, 0, 0, 0.978404,1.96082e-05)    );
  // itree = 170
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981125,-0.00310123) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.0512589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971004,0.000362644) , 
1, 116.272, 0, 0, 0.973746,0.00190012) , 
1, 121.062, 0, 0, 0.978404,2.12731e-05)    );
  // itree = 171
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.989796,0.0115461) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976374,-0.000659403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.945946,-0.0320199) , 
2, 176.933, 1, 0, 0.975862,-0.000638392) , 
3, 768.048, 0, 0, 0.978404,2.23426e-05)    );
  // itree = 172
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00107253) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984615,0.0215485) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971429,-0.0226263) , 
2, 120.856, 1, 0, 0.974046,-0.00480815) , 
1, 298.675, 1, 0, 0.978404,2.15688e-05)    );
  // itree = 173
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.989796,0.0113266) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976482,0.001614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.973805,-0.012697) , 
1, 170.104, 1, 0, 0.975862,-0.000623588) , 
3, 768.048, 0, 0, 0.978404,2.10309e-05)    );
  // itree = 174
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.001025) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984615,0.0202305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971429,-0.0206772) , 
2, 120.856, 1, 0, 0.974046,-0.004589) , 
1, 298.675, 1, 0, 0.978404,2.07624e-05)    );
  // itree = 175
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.988221,0.00972133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976256,-0.000505964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958333,-0.0412025) , 
2, 132.48, 1, 0, 0.975782,-0.000711852) , 
2, 136.964, 0, 0, 0.978404,2.00694e-05)    );
  // itree = 176
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985693,0.00444531) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.972532,-0.000801574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.930556,-0.0317541) , 
4, 113.507, 1, 0, 0.971022,-0.00133913) , 
4, 117.413, 0, 0, 0.978404,2.01296e-05)    );
  // itree = 177
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.0503612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.976849,-0.000748243) , 
4, 280.597, 0, 0, 0.978729,0.000179904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.955357,-0.0178044) , 
0, 11.9152, 0, 0, 0.978404,1.97662e-05)    );
  // itree = 178
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980101,-0.00256994) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979965,0.00922797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.949309,-0.0148857) , 
1, 75.9962, 0, 0, 0.975092,0.00190508) , 
4, 83.5821, 0, 0, 0.978404,2.03586e-05)    );
  // itree = 179
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000580866) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.990741,0.0356629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.962121,-0.00119171) , 
2, 46.6673, 1, 0, 0.975,0.00846022) , 
1, 62.7415, 0, 0, 0.978404,2.03238e-05)    );
  // itree = 180
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979466,0.00139238) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984645,0.0142775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.95979,-0.0221833) , 
1, 178.675, 0, 0, 0.971638,-0.00347617) , 
4, 21.8905, 0, 0, 0.978404,1.91527e-05)    );
  // itree = 181
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.00105528) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.993976,0.028234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.96728,-0.0193342) , 
2, 263.913, 0, 0, 0.974046,-0.00474669) , 
1, 298.675, 1, 0, 0.978404,1.95825e-05)    );
  // itree = 182
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980818,-0.00198724) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976438,0.0115687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.944134,-0.0180374) , 
2, 50.2994, 0, 0, 0.970017,0.00256777) , 
1, 99.8546, 0, 0, 0.978404,1.90603e-05)    );
  // itree = 183
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978853,-0.000737464) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.982379,0.0255523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.942623,-0.0126906) , 
4, 55.3731, 0, 0, 0.968481,0.00702613) , 
2, 45.9352, 0, 0, 0.978404,1.95136e-05)    );
  // itree = 184
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000553602) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991667,0.0356477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958333,-0.00271104) , 
4, 49.1393, 1, 0, 0.975,0.00804762) , 
1, 62.7415, 0, 0, 0.978404,1.88292e-05)    );
  // itree = 185
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.98576,0.00685992) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976604,0.00214037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.973129,-0.0140186) , 
0, 94.0277, 1, 0, 0.97568,-0.000790652) , 
0, 130.713, 0, 0, 0.978404,1.78331e-05)    );
  // itree = 186
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97868,-0.000500486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.991935,0.0380929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.94,-0.0103836) , 
4, 67.5224, 0, 0, 0.96875,0.00780047) , 
2, 41.8593, 0, 0, 0.978404,1.80269e-05)    );
  // itree = 187
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980492,0.00116635) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.96,0.0106651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958159,-0.0227508) , 
3, 331.579, 1, 0, 0.958869,-0.0040467) , 
2, 54.087, 0, 0, 0.978404,1.74864e-05)    );
  // itree = 188
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.986842,0.0243881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.979329,-0.00038823) , 
1, 65.4273, 1, 0, 0.979545,0.000188293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.912409,-0.0070753) , 
3, 284.148, 0, 0, 0.978404,1.77284e-05)    );
  // itree = 189
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979829,0.00137022) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.982327,0.00946394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.952772,-0.0201676) , 
4, 91.5423, 0, 0, 0.969983,-0.00313252) , 
0, 40.1297, 0, 0, 0.978404,1.68039e-05)    );
  // itree = 190
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980101,-0.00264361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979965,0.00912423) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.949309,-0.0139526) , 
1, 75.9962, 0, 0, 0.975092,0.0019453) , 
4, 83.5821, 0, 0, 0.978404,1.69148e-05)    );
  // itree = 191
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978853,-0.00065879) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.971545,0.017557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.961165,-0.0225433) , 
0, 100.787, 1, 0, 0.968481,0.00627596) , 
2, 45.9352, 0, 0, 0.978404,1.71129e-05)    );
  // itree = 192
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.97879,0.000961489) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984615,0.0197939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971429,-0.0193065) , 
2, 120.856, 1, 0, 0.974046,-0.00433323) , 
1, 298.675, 1, 0, 0.978404,1.63719e-05)    );
  // itree = 193
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.989796,0.0108605) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976374,-0.000621809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.945946,-0.0282968) , 
2, 176.933, 1, 0, 0.975862,-0.000594926) , 
3, 768.048, 0, 0, 0.978404,1.59743e-05)    );
  // itree = 194
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.978508,-0.000503997) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.992806,0.0351914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.950495,-0.00464751) , 
0, 57.6497, 0, 0, 0.975,0.00727878) , 
1, 62.7415, 0, 0, 0.978404,1.55933e-05)    );
  // itree = 195
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.985693,0.00424192) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.975092,0.0033633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.962294,-0.0134067) , 
4, 83.2388, 1, 0, 0.971022,-0.00128041) , 
4, 117.413, 0, 0, 0.978404,1.49226e-05)    );
  // itree = 196
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.979466,0.00131348) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.984645,0.0132275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.95979,-0.019965) , 
1, 178.675, 0, 0, 0.971638,-0.00329185) , 
4, 21.8905, 0, 0, 0.978404,1.53848e-05)    );
  // itree = 197
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980823,-0.00533638) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.997294,0.0375398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.973708,-0.000193166) , 
4, 190.567, 0, 0, 0.977067,0.00102256) , 
1, 170.104, 0, 0, 0.978404,1.57981e-05)    );
  // itree = 198
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.981125,-0.00276923) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.0511692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.971004,0.000290994) , 
1, 116.272, 0, 0, 0.973746,0.00169932) , 
1, 121.062, 0, 0, 0.978404,1.70926e-05)    );
  // itree = 199
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.980818,-0.00183293) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.976438,0.0111113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.944134,-0.0174047) , 
2, 50.2994, 0, 0, 0.970017,0.00237665) , 
1, 99.8546, 0, 0, 0.978404,1.82571e-05)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
