python mcPlots.py -P /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD -j 6 -f -l 19.6 mca-2lss-dataBCat4Plots.txt --showRatio --maxRatioRange 0 3.7 --poisson bins/2lss_em_23j.txt bins/mvaVars_2lss_23j_1.txt -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/2_finalmva_2lss_v2/evVarFriend_{cname}.root --FM sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/0_SFs_v2/sfFriend_{cname}.root -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/1_finalmva_3l_all_vars/evVarFriend_{cname}.root -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/0_finalmva_2lss_cats/evVarFriend_{cname}.root -W 'puWeight*Eff_2lep*SF_btag*SF_LepMVATight_2l*SF_LepTightCharge_2l*SF_trig2l' --pdir plots/250513/v4.2/2lss_BCat4Plots/em/23j -X 2B --tree ttHLepTreeProducerBase -p 'ttH,TT' --sp 'ttH' --plotmode=nostack --scaleSBTo1

python mcPlots.py -P /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD -j 6 -f -l 19.6 mca-2lss-dataBCat4Plots.txt --showRatio --maxRatioRange 0 3.7 --poisson bins/2lss_ee_23j.txt bins/mvaVars_2lss_23j_1.txt -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/2_finalmva_2lss_v2/evVarFriend_{cname}.root --FM sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/0_SFs_v2/sfFriend_{cname}.root -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/1_finalmva_3l_all_vars/evVarFriend_{cname}.root -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/0_finalmva_2lss_cats/evVarFriend_{cname}.root -W 'puWeight*Eff_2lep*SF_btag*SF_LepMVATight_2l*SF_LepTightCharge_2l*SF_trig2l' --pdir plots/250513/v4.2/2lss_BCat4Plots/ee/23j -X 2B --tree ttHLepTreeProducerBase -p 'ttH,TT' --sp 'ttH' --plotmode=nostack --scaleSBTo1

python mcPlots.py -P /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD -j 6 -f -l 19.6 mca-2lss-dataBCat4Plots.txt --showRatio --maxRatioRange 0 3.7 --poisson bins/2lss_mumu_23j.txt bins/mvaVars_2lss_23j_1.txt -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/2_finalmva_2lss_v2/evVarFriend_{cname}.root --FM sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/0_SFs_v2/sfFriend_{cname}.root -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/1_finalmva_3l_all_vars/evVarFriend_{cname}.root -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/0_finalmva_2lss_cats/evVarFriend_{cname}.root -W 'puWeight*Eff_2lep*SF_btag*SF_LepMVATight_2l*SF_LepTightCharge_2l*SF_trig2l' --pdir plots/250513/v4.2/2lss_BCat4Plots/mumu/23j -X 2B --tree ttHLepTreeProducerBase -p 'ttH,TT' --sp 'ttH' --plotmode=nostack --scaleSBTo1


python mcPlots.py -P /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD -j 6 -f -l 19.6 mca-2lss-dataBCat4Plots.txt --showRatio --maxRatioRange 0 3.7 --poisson bins/2lss_em_4j.txt bins/mvaVars_2lss_4j_1.txt -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/2_finalmva_2lss_v2/evVarFriend_{cname}.root --FM sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/0_SFs_v2/sfFriend_{cname}.root -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/1_finalmva_3l_all_vars/evVarFriend_{cname}.root -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/0_finalmva_2lss_cats/evVarFriend_{cname}.root -W 'puWeight*Eff_2lep*SF_btag*SF_LepMVATight_2l*SF_LepTightCharge_2l*SF_trig2l' --pdir plots/250513/v4.2/2lss_BCat4Plots/em/4j -X 2B --tree ttHLepTreeProducerBase -p 'ttH,TT' --sp 'ttH' --plotmode=nostack --scaleSBTo1

python mcPlots.py -P /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD -j 6 -f -l 19.6 mca-2lss-dataBCat4Plots.txt --showRatio --maxRatioRange 0 3.7 --poisson bins/2lss_ee_4j.txt bins/mvaVars_2lss_4j_1.txt -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/2_finalmva_2lss_v2/evVarFriend_{cname}.root --FM sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/0_SFs_v2/sfFriend_{cname}.root -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/1_finalmva_3l_all_vars/evVarFriend_{cname}.root -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/0_finalmva_2lss_cats/evVarFriend_{cname}.root -W 'puWeight*Eff_2lep*SF_btag*SF_LepMVATight_2l*SF_LepTightCharge_2l*SF_trig2l' --pdir plots/250513/v4.2/2lss_BCat4Plots/ee/4j -X 2B --tree ttHLepTreeProducerBase -p 'ttH,TT' --sp 'ttH' --plotmode=nostack --scaleSBTo1

python mcPlots.py -P /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD -j 6 -f -l 19.6 mca-2lss-dataBCat4Plots.txt --showRatio --maxRatioRange 0 3.7 --poisson bins/2lss_mumu_4j.txt bins/mvaVars_2lss_4j_1.txt -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/2_finalmva_2lss_v2/evVarFriend_{cname}.root --FM sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/0_SFs_v2/sfFriend_{cname}.root -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/1_finalmva_3l_all_vars/evVarFriend_{cname}.root -F sf/t /afs/cern.ch/work/m/mdjordje/TTH/TREES_250513_HADD/0_finalmva_2lss_cats/evVarFriend_{cname}.root -W 'puWeight*Eff_2lep*SF_btag*SF_LepMVATight_2l*SF_LepTightCharge_2l*SF_trig2l' --pdir plots/250513/v4.2/2lss_BCat4Plots/mumu/4j -X 2B --tree ttHLepTreeProducerBase -p 'ttH,TT' --sp 'ttH' --plotmode=nostack --scaleSBTo1

