python mcPlots.py -P /afs/cern.ch/work/c/cirkovic/Retraining_200914/CMSSW_5_3_19/src/CMGTools/TTHAnalysis/cfg/OUTPUT -j 6 -f -l 19.6 mca-2lss-dataBCat4Plots_TTH_TTJets.txt bins/2lss_mumu.txt bins/2lss_topReco_plots.txt -F sf/t /afs/cern.ch/work/c/cirkovic/Retraining_200914/CMSSW_5_3_19/src/CMGTools/TTHAnalysis/macros/FT_OUTPUT/evVarFriend_{cname}.root --pdir plots/210914/vars/mumu --tree treeProducerSusyMultilepton --plotmode=nostack --s2v #-X 'lep MVA' # -X 'cleanup' -X 'pt2010' -X 'pt2020_htllv100' -X '4j' -X '2b loose' -X '2B tight' -X '2 good leptons'

python mcPlots.py -P /afs/cern.ch/work/c/cirkovic/Retraining_200914/CMSSW_5_3_19/src/CMGTools/TTHAnalysis/cfg/OUTPUT -j 6 -f -l 19.6 mca-2lss-dataBCat4Plots_TTH_TTJets.txt bins/2lss_ee.txt   bins/2lss_topReco_plots.txt -F sf/t /afs/cern.ch/work/c/cirkovic/Retraining_200914/CMSSW_5_3_19/src/CMGTools/TTHAnalysis/macros/FT_OUTPUT/evVarFriend_{cname}.root --pdir plots/210914/vars/ee   --tree treeProducerSusyMultilepton --plotmode=nostack --s2v #-X 'lep MVA' # -X 'cleanup' -X 'pt2010' -X 'pt2020_htllv100' -X '4j' -X '2b loose' -X '2B tight' -X '2 good leptons'

python mcPlots.py -P /afs/cern.ch/work/c/cirkovic/Retraining_200914/CMSSW_5_3_19/src/CMGTools/TTHAnalysis/cfg/OUTPUT -j 6 -f -l 19.6 mca-2lss-dataBCat4Plots_TTH_TTJets.txt bins/2lss_em.txt   bins/2lss_topReco_plots.txt -F sf/t /afs/cern.ch/work/c/cirkovic/Retraining_200914/CMSSW_5_3_19/src/CMGTools/TTHAnalysis/macros/FT_OUTPUT/evVarFriend_{cname}.root --pdir plots/210914/vars/em   --tree treeProducerSusyMultilepton --plotmode=nostack --s2v #-X 'lep MVA' # -X 'cleanup' -X 'pt2010' -X 'pt2020_htllv100' -X '4j' -X '2b loose' -X '2B tight' -X '2 good leptons'


python rocCurves.py -P /afs/cern.ch/work/c/cirkovic/Retraining_200914/CMSSW_5_3_19/src/CMGTools/TTHAnalysis/cfg/OUTPUT -j 6 -f -l 19.6 mca-2lss-dataBCat4Plots_TTH_TTJets.txt bins/2lss_mumu.txt roc_2lss.txt -F sf/t /afs/cern.ch/work/c/cirkovic/Retraining_200914/CMSSW_5_3_19/src/CMGTools/TTHAnalysis/macros/FT_OUTPUT/evVarFriend_{cname}.root -o plots/210914/roc/mumu --tree treeProducerSusyMultilepton --s2v -X 'cleanup' -X 'pt2010' -X 'pt2020_htllv100' -X '4j' -X '2b loose' -X '2B tight' -X 'lep MVA' -X '2 good leptons'

python rocCurves.py -P /afs/cern.ch/work/c/cirkovic/Retraining_200914/CMSSW_5_3_19/src/CMGTools/TTHAnalysis/cfg/OUTPUT -j 6 -f -l 19.6 mca-2lss-dataBCat4Plots_TTH_TTJets.txt bins/2lss_em.txt roc_2lss.txt -F sf/t /afs/cern.ch/work/c/cirkovic/Retraining_200914/CMSSW_5_3_19/src/CMGTools/TTHAnalysis/macros/FT_OUTPUT/evVarFriend_{cname}.root -o plots/210914/roc/em --tree treeProducerSusyMultilepton --s2v -X 'cleanup' -X 'pt2010' -X 'pt2020_htllv100' -X '4j' -X '2b loose' -X '2B tight' -X 'lep MVA' -X '2 good leptons'

python rocCurves.py -P /afs/cern.ch/work/c/cirkovic/Retraining_200914/CMSSW_5_3_19/src/CMGTools/TTHAnalysis/cfg/OUTPUT -j 6 -f -l 19.6 mca-2lss-dataBCat4Plots_TTH_TTJets.txt bins/2lss_mumu.txt roc_2lss.txt -F sf/t /afs/cern.ch/work/c/cirkovic/Retraining_200914/CMSSW_5_3_19/src/CMGTools/TTHAnalysis/macros/FT_OUTPUT/evVarFriend_{cname}.root -o plots/210914/roc/ee --tree treeProducerSusyMultilepton --s2v -X 'cleanup' -X 'pt2010' -X 'pt2020_htllv100' -X '4j' -X '2b loose' -X '2B tight' -X 'lep MVA' -X '2 good leptons'

